name: Publish Release to npm

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run tests and coverage
      run: bun run test

    - name: Build the project
      run: bun run build

    - name: Publish to npm
      env:
        NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: bun publish -p --access public
